name: Release Deployment

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: deploy-release
  cancel-in-progress: false

jobs:
  release:
    name: Publish Release Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Required for commit range detection
          ref: main

      - name: Generate Changelog
        id: gitwit
        uses: rafandoo/gitwit-action@v1.1.0-RC2
        with:
          command: changelog
          changelog_stdout: true
          changelog_from_latest_release: true

      - name: Generate Changelog
        id: gitwit_2
        uses: rafandoo/gitwit-action@v1.1.0-RC2
        with:
          command: changelog
          changelog_from_latest_release: true
          args: --append

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ${{ steps.gitwit.outputs.changelog }}

      - name: Commit Changelog Update
        uses: EndBug/add-and-commit@v9
        with:
          message: ":alarm_clock:: update changelog for release ${{ github.ref_name }}"
          default_author: github_actions